name: "CI Build"

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: ./gradle/java-version.txt
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew check"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  package:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: ./gradle/java-version.txt
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew assemble${{ matrix.os }}"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}
      - uses: actions/upload-artifact@v4
        with:
          name: Application Package ${{ matrix.os }}
          path: build/app/packages/*/*