name: "CI Build"

on: [ push ]

env:
  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
  BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: ./gradle/java-version.txt
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew test"

  package:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: ./gradle/java-version.txt
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew test${{ matrix.os }}"
      - uses: gradle/actions/setup-gradle@v3
      - run: "./gradlew assemble${{ matrix.os }}"
      - uses: actions/upload-artifact@v4
        with:
          name: Application Package ${{ matrix.os }}
          path: build/app/packages/*/*
