name: "CI Build"

on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3.1.0
      - run: "./gradlew check"

  package:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3.1.0
      - run: "./gradlew assemble${{ matrix.os }}"
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: Application Package ${{ matrix.os }}
          path: modules/app/build/packages/*/*